#!/usr/bin/env python3
"""
uberwiki_cli.py — UberWiki orchestrator CLI.

Commands:
  init            Bootstrap .wiki/ structure
  sync            Incremental scan + trie + llmwiki index
  sync --full     Full rebuild from scratch
  ingest <path>   Add specific file(s)
  query <text>    Search both layers, return ≤400 tokens
  profile         Suggest BPE compound merges
  apply-merges    Apply suggested merges
  bridge          Export to Android JSON
  serve           Start llmwiki MCP server
  status          Show wiki stats

Usage:
  python uberwiki_cli.py init --path . --topic "My Project"
  python uberwiki_cli.py sync --full --path .
  python uberwiki_cli.py query "memory compression" --path .
"""

from __future__ import annotations
import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

# ── Imports from sibling scripts ──────────────────────────────────────
SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from dynamic_vector_trie import DynamicVectorTrie
from file_scanner import (scan_project, load_hash_cache, save_hash_cache,
                          compute_diff, extract_structural_lines)
from vector_decompress import decompress_hierarchical, export_to_json

try:
    from bpe_radix_profiler import BPERadixProfiler
    HAS_BPE = True
except ImportError:
    HAS_BPE = False


# ── Paths ─────────────────────────────────────────────────────────────

def wiki_dir(root: Path) -> Path:
    return root / ".wiki"


def human_dir(root: Path) -> Path:
    return wiki_dir(root) / "human"


def ai_dir(root: Path) -> Path:
    return wiki_dir(root) / "ai"


def trie_path(root: Path) -> Path:
    return ai_dir(root) / "wiki.trie"


def dict_path(root: Path) -> Path:
    return ai_dir(root) / "wiki.dict"


def hash_cache_path(root: Path) -> Path:
    return ai_dir(root) / "file_hashes.json"


def bridge_path(root: Path) -> Path:
    return ai_dir(root) / "bridge.json"


# ── Commands ──────────────────────────────────────────────────────────

def cmd_init(args):
    root = Path(args.path).resolve()
    hd = human_dir(root)
    ad = ai_dir(root)

    for d in [hd / "raw", hd / "entities", hd / "concepts",
              hd / "sources", hd / "comparisons", hd / "synthesis",
              ad]:
        d.mkdir(parents=True, exist_ok=True)

    # index.md
    index_path = hd / "index.md"
    if not index_path.exists():
        topic = args.topic or Path(root).name
        index_path.write_text(
            f"# {topic} — Wiki Index\n\n"
            f"_Auto-generated by uberwiki_\n\n"
            f"## Concepts\n\n"
            f"## Entities\n\n"
            f"## Sources\n\n"
        )

    # log.md
    log_path = hd / "log.md"
    if not log_path.exists():
        log_path.write_text(
            "# Wiki Log\n\n"
            f"## [{time.strftime('%Y-%m-%d %H:%M')}] init | uberwiki\n"
            f"Initialized wiki for {root.name}\n\n"
        )

    # .gitignore for .index/
    ad_gitignore = ad / ".gitignore"
    if not ad_gitignore.exists():
        ad_gitignore.write_text(".index/\nfile_hashes.json\n")

    print(f"Initialized wiki at {wiki_dir(root)}")
    print(f"  Human: {hd}")
    print(f"  AI:    {ad}")
    print(f"Run 'uberwiki_cli sync --full' to index the project.")


def cmd_sync(args):
    root = Path(args.path).resolve()
    ad = ai_dir(root)
    ad.mkdir(parents=True, exist_ok=True)

    start = time.time()

    if args.full:
        print("Full sync: scanning all files...")
        files = scan_project(root)
        trie = DynamicVectorTrie()
        print(f"  Found {len(files)} files, indexing...")
        _insert_files(trie, files, root)
        trie.serialize(trie_path(root))
        new_hashes = {f["path"]: f["hash"] for f in files}
        save_hash_cache(hash_cache_path(root), new_hashes)
        print(f"  Trie: {len(trie.pool)} nodes, {len(trie.dictionary)} tokens")
        elapsed = time.time() - start
        print(f"Full sync complete in {elapsed:.1f}s")

        # llmwiki index
        _run_llmwiki_index(root)
    else:
        print("Incremental sync: scanning for changes...")
        files = scan_project(root)
        cached = load_hash_cache(hash_cache_path(root))
        diff = compute_diff(files, cached)

        if diff["summary"]["new"] == 0 and diff["summary"]["changed"] == 0 and diff["summary"]["deleted"] == 0:
            print("  No changes detected.")
            return

        print(f"  New: {diff['summary']['new']}, Changed: {diff['summary']['changed']}, "
              f"Deleted: {diff['summary']['deleted']}")

        # Load existing trie
        trie_path_obj = trie_path(root)
        if trie_path_obj.exists():
            trie = DynamicVectorTrie().deserialize(trie_path_obj)
        else:
            trie = DynamicVectorTrie()

        # Delete removed files
        for del_path in diff["deleted"]:
            # Remove all terminal nodes for this path
            tid_path = trie.tokenize_path(del_path)
            # We can't easily delete all children under a prefix without a full sweep
            # For now, mark the file path node as non-terminal
            idx = trie._walk(tid_path)
            if idx is not None:
                trie.pool[idx][3] = False

        # Insert/update new and changed files
        changed_files = diff["new"] + diff["changed"]
        if changed_files:
            _insert_files(trie, changed_files, root)

        trie.serialize(trie_path(root))
        new_hashes = {f["path"]: f["hash"] for f in files}
        save_hash_cache(hash_cache_path(root), new_hashes)
        print(f"  Trie: {len(trie.pool)} nodes, {len(trie.dictionary)} tokens")
        elapsed = time.time() - start
        print(f"Incremental sync complete in {elapsed:.1f}s")

        if changed_files:
            _run_llmwiki_index(root)


def cmd_ingest(args):
    root = Path(args.path).resolve()
    ad = ai_dir(root)
    ad.mkdir(parents=True, exist_ok=True)

    target = Path(args.target).resolve()
    if not target.exists():
        print(f"Error: {target} not found")
        return 1

    # Load trie
    trie_path_obj = trie_path(root)
    if trie_path_obj.exists():
        trie = DynamicVectorTrie().deserialize(trie_path_obj)
    else:
        trie = DynamicVectorTrie()

    files_to_process = []
    if target.is_file():
        files_to_process.append(target)
    else:
        for f in target.rglob("*"):
            if f.is_file():
                files_to_process.append(f)

    valid_files = []
    for f in files_to_process:
        try:
            rel = f.relative_to(root)
        except ValueError:
            rel = f.name

        ext = f.suffix.lower()
        try:
            content = f.read_bytes()
            if b"\x00" in content[:512]:
                continue
        except Exception:
            continue

        valid_files.append({"path": str(rel), "abs_path": str(f), "ext": ext})

    if not valid_files:
        print("No valid text files found.")
        return

    print(f"Ingesting {len(valid_files)} files...")
    _insert_files(trie, valid_files, root)
    trie.serialize(trie_path(root))
    print(f"  Trie: {len(trie.pool)} nodes, {len(trie.dictionary)} tokens")


def cmd_query(args):
    root = Path(args.path).resolve()
    trie_path_obj = trie_path(root)
    if not trie_path_obj.exists():
        print("No wiki trie found. Run 'uberwiki_cli sync --full' first.")
        return 1

    trie = DynamicVectorTrie().deserialize(trie_path_obj)

    query = " ".join(args.query)
    dict_set = set(trie.dictionary)

    def try_search(tokens):
        return trie.prefix_search_flat(tokens, max_tokens=400)

    # Try exact case first
    words = query.split()
    for c in [words, [query], [w.lower() for w in words], [query.lower()]]:
        result = try_search(c)
        if result:
            print(result)
            return

    # Fallback: try individual words
    for word in words:
        result = try_search([word])
        if result:
            print(result)
            return
        result = try_search([word.lower()])
        if result:
            print(result)
            return

    # Try matching against dictionary tokens
    matches = [t for t in dict_set if any(w.lower() in t.lower() for w in words)]
    for m in matches[:3]:
        result = try_search([m])
        if result:
            print(result)
            return

    # Last resort: show top-level trie structure
    top_tokens = [t for t in dict_set if "/" not in t and "|" not in t]
    for t in top_tokens[:5]:
        result = try_search([t])
        if result and len(result) > 50:
            print(result)
            return
    print("No results found.")


def cmd_profile(args):
    root = Path(args.path).resolve()
    trie_path_obj = trie_path(root)
    if not trie_path_obj.exists():
        print("No wiki trie found. Run 'uberwiki_cli sync --full' first.")
        return 1

    if not HAS_BPE:
        print("BPE profiler not available.")
        return 1

    trie = DynamicVectorTrie().deserialize(trie_path_obj)
    profiler = BPERadixProfiler(min_frequency=args.min_freq, max_phrase_len=args.max_phrase)
    profiler.scan_trie_paths(trie)
    merges = profiler.rank_merges(top_k=args.top_k)

    if not merges:
        print("No compound merge candidates found.")
        return

    print(f"Top {len(merges)} compound merge candidates:")
    print(f"{'Freq':>5} {'Score':>7}  Merge")
    print(f"{'─'*5} {'─'*7}  {'─'*40}")
    for m in merges:
        print(f"{m['frequency']:5d} {m['score']:7.0f}  \"{m['ngram']}\" → {m['compound_symbol']}")

    # Save to file
    output = ai_dir(root) / "merge_candidates.json"
    import json as j
    output.write_text(j.dumps(merges, indent=2))
    print(f"\nCandidates saved to {output}")


def cmd_apply_merges(args):
    root = Path(args.path).resolve()
    trie_path_obj = trie_path(root)
    if not trie_path_obj.exists():
        print("No wiki trie found. Run 'uberwiki_cli sync --full' first.")
        return 1

    if not HAS_BPE:
        print("BPE profiler not available.")
        return 1

    # Load merge candidates
    candidates_path = ai_dir(root) / "merge_candidates.json"
    if not candidates_path.exists():
        print("No merge candidates found. Run 'profile' first.")
        return 1

    candidates = json.loads(candidates_path.read_text())
    if not candidates:
        print("No merge candidates to apply.")
        return

    trie = DynamicVectorTrie().deserialize(trie_path_obj)
    profiler = BPERadixProfiler()

    count = 0
    for c in candidates:
        profiler.apply_merge(trie, c["ngram"], c["compound_symbol"])
        count += 1

    trie.serialize(trie_path(root))
    print(f"Applied {count} merges. Trie: {len(trie.pool)} nodes, {len(trie.dictionary)} tokens")


def cmd_bridge(args):
    root = Path(args.path).resolve()
    trie_path_obj = trie_path(root)
    if not trie_path_obj.exists():
        print("No wiki trie found. Run 'uberwiki_cli sync --full' first.")
        return 1

    trie = DynamicVectorTrie().deserialize(trie_path_obj)
    data = export_to_json(trie)
    bp = bridge_path(root)
    bp.write_text(json.dumps(data, indent=2))
    print(f"Bridge JSON exported to {bp}")
    print(f"  {len(data['entities'])} entities, {len(data['relations'])} relations")

    if args.push:
        import subprocess as sp
        device_dir = "/sdcard/Download/uberwiki_bridge.json"
        result = sp.run(["adb", "push", str(bp), device_dir],
                        capture_output=True, text=True)
        if result.returncode == 0:
            print(f"Pushed to device: {device_dir}")
        else:
            print(f"ADB push failed: {result.stderr}")


def cmd_serve(args):
    root = Path(args.path).resolve()

    # Check if llmwiki is available
    if not shutil.which("llmwiki"):
        print("llmwiki not found. Install with: cargo install llmwiki")
        return 1

    cmd = ["llmwiki", "serve", "--wiki-root", str(human_dir(root))]
    if args.port:
        cmd.extend(["--port", str(args.port)])

    print(f"Starting llmwiki MCP server for {human_dir(root)}")
    print("Press Ctrl+C to stop.")
    try:
        subprocess.run(cmd)
    except KeyboardInterrupt:
        pass


def cmd_status(args):
    root = Path(args.path).resolve()

    print(f"Wiki root: {wiki_dir(root)}")

    # Human wiki stats
    hd = human_dir(root)
    md_files = list(hd.rglob("*.md"))
    print(f"\nHuman wiki:")
    print(f"  Markdown files: {len(md_files)}")
    print(f"  Size: {sum(f.stat().st_size for f in md_files) / 1024:.0f} KB")

    # AI wiki stats
    ad = ai_dir(root)
    print(f"\nAI wiki:")

    trie_path_obj = trie_path(root)
    if trie_path_obj.exists():
        trie = DynamicVectorTrie().deserialize(trie_path_obj)
        stats = trie.stats()
        print(f"  Trie nodes: {stats['nodes']}")
        print(f"  Dictionary tokens: {stats['tokens']}")
        print(f"  Terminal nodes: {stats['terminal_nodes']}")
        print(f"  Max depth: {stats['max_depth']}")
        print(f"  Trie file size: {trie_path_obj.stat().st_size / 1024:.0f} KB")
    else:
        print("  No trie file.")

    # Hash cache
    hc = hash_cache_path(root)
    if hc.exists():
        hashes = json.loads(hc.read_text())
        print(f"  Cached files: {len(hashes)}")

    # llmwiki index
    index_dir = ad / ".index"
    if index_dir.exists():
        index_files = sum(1 for _ in index_dir.rglob("*") if _.is_file())
        print(f"  llmwiki index files: {index_files}")

    # Bridge
    bp = bridge_path(root)
    if bp.exists():
        data = json.loads(bp.read_text())
        print(f"  Bridge export: {len(data.get('entities', []))} entities")


# ── Helpers ───────────────────────────────────────────────────────────

def _insert_files(trie: DynamicVectorTrie, files: list[dict], root: Path):
    """Insert structural lines from files into trie."""
    for i, f in enumerate(files):
        fp = Path(f["abs_path"])
        ext = f["ext"]

        # Get structural lines
        lines = extract_structural_lines(fp, ext)
        if not lines:
            # Fallback: use file path itself
            path_tids = trie.tokenize_path(f["path"])
            trie.insert(path_tids)

        # Insert each structural line as a trie path
        for line in lines:
            path_str = f"{f['path']}|{line}"
            tids = trie.tokenize_path(path_str)
            trie.insert(tids)

        if (i + 1) % 500 == 0:
            print(f"    Indexed {i + 1}/{len(files)} files...")


def _run_llmwiki_index(root: Path):
    """Run llmwiki index on human wiki."""
    hd = human_dir(root)
    if shutil.which("llmwiki"):
        try:
            subprocess.run(["llmwiki", "init", "--wiki-root", str(hd)],
                           capture_output=True, text=True, timeout=30)
            result = subprocess.run(["llmwiki", "index", "--incremental",
                                     "--wiki-root", str(hd)],
                                    capture_output=True, text=True, timeout=120)
            if result.returncode == 0:
                print(f"  llmwiki: {result.stdout.strip()}")
            else:
                print(f"  llmwiki: {result.stderr.strip()[:200]}")
        except Exception as e:
            print(f"  llmwiki: {e}")
    else:
        print("  llmwiki not found (optional). Install: cargo install llmwiki")


# ── CLI entry point ───────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="UberWiki — Two-layer compressed wiki for humans and AI",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s init --path . --topic "My Project"
  %(prog)s sync --full --path .
  %(prog)s query "memory" --path .
  %(prog)s status --path .
        """)

    sub = parser.add_subparsers(dest="command", required=True)

    # Shared arg: --path available on all subcommands
    def add_path(sp):
        sp.add_argument("--path", default=".",
                        help="Project root path (default: current dir)")

    # init
    p_init = sub.add_parser("init", help="Bootstrap .wiki/ structure")
    add_path(p_init)
    p_init.add_argument("--topic", default=None, help="Project topic name")

    # sync
    p_sync = sub.add_parser("sync", help="Sync project files into trie + llmwiki index")
    add_path(p_sync)
    p_sync.add_argument("--full", action="store_true", help="Full rebuild from scratch")

    # ingest
    p_ingest = sub.add_parser("ingest", help="Add specific file(s) to wiki")
    add_path(p_ingest)
    p_ingest.add_argument("target", help="File or directory to ingest")

    # query
    p_query = sub.add_parser("query", help="Search wiki, return ≤400 tokens")
    add_path(p_query)
    p_query.add_argument("query", nargs="+", help="Search terms")

    # profile
    p_profile = sub.add_parser("profile", help="Suggest BPE compound merges")
    add_path(p_profile)
    p_profile.add_argument("--min-freq", type=int, default=3, help="Minimum frequency (default: 3)")
    p_profile.add_argument("--max-phrase", type=int, default=4, help="Max n-gram length (default: 4)")
    p_profile.add_argument("--top-k", type=int, default=20, help="Number of candidates (default: 20)")

    # apply-merges
    p_merge = sub.add_parser("apply-merges", help="Apply suggested BPE merges")
    add_path(p_merge)

    # bridge
    p_bridge = sub.add_parser("bridge", help="Export trie as Android bridge JSON")
    add_path(p_bridge)
    p_bridge.add_argument("--push", action="store_true", help="Push to device via ADB")

    # serve
    p_serve = sub.add_parser("serve", help="Start llmwiki MCP server")
    add_path(p_serve)
    p_serve.add_argument("--port", type=int, default=8080, help="Port (default: 8080)")

    # status
    p_status = sub.add_parser("status", help="Show wiki statistics")
    add_path(p_status)

    args = parser.parse_args()

    commands = {
        "init": cmd_init,
        "sync": cmd_sync,
        "ingest": cmd_ingest,
        "query": cmd_query,
        "profile": cmd_profile,
        "apply-merges": cmd_apply_merges,
        "bridge": cmd_bridge,
        "serve": cmd_serve,
        "status": cmd_status,
    }

    fn = commands.get(args.command)
    if fn:
        try:
            return fn(args)
        except Exception as e:
            print(f"Error: {e}", file=sys.stderr)
            import traceback
            traceback.print_exc()
            return 1
    else:
        parser.print_help()
        return 1


if __name__ == "__main__":
    sys.exit(main())
